### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by dqksoftware** [codingiran/EZOpenSDK-iOS#1]
因为 萤石官网的SDK里有UIWebView 不能提交到APPstore，因此用大神提交的EZOpenSDK-iOS 解决了。

**Comment by dqksoftware** [comment]
需要 关闭bitcode  还有去萤石官网首页下载个Demo 把demo里的那个文件(大神readme文件中说的那个文件)拖入到自己项目的根目录下 就ok了。  最后 非常感谢大神

**Comment by codingiran** [comment]
请参照官方Demo将 com.hri.hpc.mobile.ios.player.metallib 拖入项目
